name: 'lifetimewarper'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install black

      - name: Install package in editable mode
        run: pip install -e .

      - name: Format code with Black
        run: black rul_timewarping tests

      - name: Check code style with Black
        run: |
          black --check rul_timewarping tests

      - name: Run tests with coverage
        run: |
          pytest --cov=rul_timewarping --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 15724e1a-a7e0-4064-ae65-df26e7e2aa5e
          files: ./coverage.xml
          fail_ci_if_error: true
